In [1]:
class net():

    def __init__(self, a):
        self.a = a
    
    @staticmethod
    def forward(x):
        return 4*x

In [2]:
net.forward(3)

12

In [10]:
import torch.nn as nn

In [11]:
a = nn.Identity(1)

In [13]:
import torch

In [14]:
input = torch.randn(128, 20)


In [15]:
input

tensor([[ 3.0143,  1.2041,  0.4272,  ...,  0.3461, -0.7800,  0.4538],
        [ 1.1819, -0.0367, -1.4793,  ..., -1.5586, -1.2380, -1.1934],
        [ 0.6807, -1.3197, -0.4051,  ...,  0.3509, -0.9833,  0.1027],
        ...,
        [-0.2542,  0.8347, -0.5509,  ...,  0.0244, -0.5026, -0.3903],
        [-0.0840,  0.8555, -1.8857,  ..., -1.5121, -1.7676,  0.8608],
        [ 0.4732,  0.2405,  0.4609,  ...,  0.8439, -0.9908,  0.0318]])

In [16]:
output = a(input)

In [17]:
output

tensor([[ 3.0143,  1.2041,  0.4272,  ...,  0.3461, -0.7800,  0.4538],
        [ 1.1819, -0.0367, -1.4793,  ..., -1.5586, -1.2380, -1.1934],
        [ 0.6807, -1.3197, -0.4051,  ...,  0.3509, -0.9833,  0.1027],
        ...,
        [-0.2542,  0.8347, -0.5509,  ...,  0.0244, -0.5026, -0.3903],
        [-0.0840,  0.8555, -1.8857,  ..., -1.5121, -1.7676,  0.8608],
        [ 0.4732,  0.2405,  0.4609,  ...,  0.8439, -0.9908,  0.0318]])

In [18]:
a = torch.randn(2, 3)

In [19]:
a

tensor([[-1.2605, -0.2346,  2.0546],
        [-1.1974,  0.4111,  0.9541]])

In [20]:
b = torch.randn(2, 3)

In [21]:
b

tensor([[1.6435, 0.3345, 1.4878],
        [0.7618, 0.6400, 0.4324]])

In [22]:
c = torch.stack([a, b], dim = -1)

In [23]:
c

tensor([[[-1.2605,  1.6435],
         [-0.2346,  0.3345],
         [ 2.0546,  1.4878]],

        [[-1.1974,  0.7618],
         [ 0.4111,  0.6400],
         [ 0.9541,  0.4324]]])

In [25]:
c.size()

torch.Size([2, 3, 2])

In [26]:
c_1 = torch.stack([a, b], dim = 0)

In [29]:
c_1

tensor([[[-1.2605, -0.2346,  2.0546],
         [-1.1974,  0.4111,  0.9541]],

        [[ 1.6435,  0.3345,  1.4878],
         [ 0.7618,  0.6400,  0.4324]]])

In [30]:
c_1.size()

torch.Size([2, 2, 3])

In [31]:
c_2 = torch.stack([a, b], dim = 1)

In [32]:
c_2

tensor([[[-1.2605, -0.2346,  2.0546],
         [ 1.6435,  0.3345,  1.4878]],

        [[-1.1974,  0.4111,  0.9541],
         [ 0.7618,  0.6400,  0.4324]]])

In [1]:
import torch

In [2]:
a = torch.randn(2, 3)

In [3]:
b = torch.randn(2, 3)

In [4]:
a.size()

torch.Size([2, 3])

In [5]:
c_1 = torch.stack([a, b], dim = -1)

In [6]:
c_1.size()

torch.Size([2, 3, 2])

In [7]:
a = a.view(1,6, -1)

In [8]:
a

tensor([[[-0.5367],
         [ 0.0800],
         [ 0.4719],
         [ 0.0448],
         [ 1.3884],
         [-0.5123]]])

In [9]:
import numpy as np

In [32]:
a = np.random.randn(1, 9)

In [33]:
b = a.reshape(3, 3)

In [34]:
c = b.reshape(1, 3, 3)

In [35]:
c

array([[[ 1.14709717, -0.25214519, -0.89028005],
        [ 0.47826312,  1.29786411, -0.37218257],
        [-1.57584331, -1.05738641, -0.55134829]]])

In [40]:
c[0]

array([[ 1.14709717, -0.25214519, -0.89028005],
       [ 0.47826312,  1.29786411, -0.37218257],
       [-1.57584331, -1.05738641, -0.55134829]])

In [36]:
a = np.argmax(c, 1)

In [37]:
a

array([[0, 1, 1]], dtype=int64)

In [41]:
b = np.argmax(c, 1)

In [42]:
b

array([[0, 1, 1]], dtype=int64)